---
title: "Homework2"
author: "Akash Setti, Anuraag Pujari, Gauthaman Sethupathy, Siddarthan Prakash"
date: "2/9/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
```


```{r}
gapdf <- read.csv("gapminder-5060.csv", TRUE, ",")
head(gapdf)
```

```{r, echo=FALSE}
canada <- gapdf[gapdf$country == "Canada", ]
canada %>%
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point() + geom_line()
```


```{r, echo=TRUE}
canada_fixed <- canada %>% mutate(
  lifeExp = replace(lifeExp, year==1957, 69.96)
)
head(canada_fixed)
```


```{r}
US <- gapdf[gapdf$country == "United States", ]
US %>%
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point() + geom_line()
```

```{r}
AUS <- gapdf[gapdf$country == "Australia", ]
AUS %>%
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point() + geom_line()
```
```{r}
canada_fixed %>%
ggplot(aes(x = lifeExp, y = gdpPercap, group = country)) + geom_line() +
geom_line(data = gapdf %>%
            filter(country %in% c("United States", "Australia")))
```
